[agentd]
auto_start_daemon = true
tail_default = 200
non_interactive = false

[mcu.usb_hub]
backend = "espflash"
chip = "esp32s3"
artifact_elf = "target/xtensa-esp32s3-none-elf/release/isolapurr-usb-hub"
selector_cache_file = ".esp32-port"

[mcu.usb_hub.espflash]
log_format = "defmt"
after_flash = "no-reset"
skip_update_check = true
