[target.xtensa-esp32s3-none-elf]
runner = "bash tools/mcu-agentd-runner"
rustflags = ["-C", "link-arg=-nostartfiles"]

[env]
DEFMT_LOG = "info"

[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]
